### ISSUE TITLE
Add extensive Info section.

### ISSUE THREAD

**Issue by ShahSunny** [ShahSunny/mysql-redshift-import#6]
- Info shall provide
  - Redshift table
  - MySQL table
  - Append mode.
  - fields to import, fields rejected
  - Mapping of MySql to Redshift types
  - Neglected fields for the sort-keys
  - Primary keys and sort keys found
  - count of the total rows
  - count of the rows per each partition

**Comment by shivamsharma** [comment]
I am taking this issue...@sunny

**Comment by sunny** [comment]
I think you meant @ShahSunny ;)

**Comment by shivamsharma** [comment]
😄 Yeah sorry, in hurry I typed. @sunny  😛 😛
